AppBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: AppBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            length: '255'
            unique: true
            options:
                comment: 'User email'
        password:
            type: string
            length: '64'
            options:
                comment: 'User password'
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: persons
            joinTable:
                name: persons_roles
                joinColumns:
                    person_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
